### ISSUE TITLE
Support for Caddy 2.5.0

### ISSUE THREAD

**Issue by idontusenumbers** [gamalan/caddy-tlsredis#40]
Any timeline for an updated release that's compatible with Caddy 2.5.0? I just tried running a build with 2.5.0 and ran into some go compile errors that seem to have been addressed at least in part by a precent commit:

```
FROM caddy:2.5.0-builder AS builder

RUN xcaddy build \
    --with github.com/gamalan/caddy-tlsredis
```

```
#85 76.10 # github.com/gamalan/caddy-tlsredis
#85 76.10 /go/pkg/mod/github.com/gamalan/caddy-tlsredis@v0.2.8/storageredis.go:159:9: cannot use rd (variable of type *RedisStorage) as type certmagic.Storage in return statement:
#85 76.10 	*RedisStorage does not implement certmagic.Storage (wrong type for Delete method)
#85 76.10 		have Delete(key string) error
#85 76.10 		want Delete(ctx context.Context, key string) error
#85 76.10 /go/pkg/mod/github.com/gamalan/caddy-tlsredis@v0.2.8/storageredis.go:484:25: undefined: certmagic.ErrNotExist
#85 75.15 # github.com/gamalan/caddy-tlsredis
#85 75.15 /go/pkg/mod/github.com/gamalan/caddy-tlsredis@v0.2.8/storageredis.go:159:9: cannot use rd (variable of type *RedisStorage) as type certmagic.Storage in return statement:
#85 75.15 	*RedisStorage does not implement certmagic.Storage (wrong type for Delete method)
#85 75.15 		have Delete(key string) error
#85 75.15 		want Delete(ctx context.Context, key string) error
#85 75.15 /go/pkg/mod/github.com/gamalan/caddy-tlsredis@v0.2.8/storageredis.go:484:25: undefined: certmagic.ErrNotExist
```
